export default{
  COLORS: {
    BACKGROUND_HEADER: "#030309ff",
     BACKGROUND_FOOTER: "#030309ff",
    BACKGROUND_COLOR: "#2d2e2e",
    FONTS_COLORS_LIGHT: "#fff",
    FONTS_COLORS_LIST: "#B0B4B4",
    FONTS_COLORS_LINKS: "#fff"
  }
}